{% set name = "python-language-server" %}
{% set version = "0.11.1" %}
{% set hash_type = "sha256" %}
{% set hash = "df27f7112327f671e7679ab8cd3ec29e718f7c80fc49c3d595520525f0186d0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/palantir/{{ name }}/archive/{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyls = pyls.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - configparser  # [py27 or py34]
    - future
    - jedi >=0.10
    - json-rpc
    - pycodestyle
    - pyflakes
    - python
    - yapf
    - pluggy
    - rope >=0.10.5

test:
  commands:
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol 
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
