{% set name = "python-language-server" %}
{% set version = "0.31.4" %}
{% set hash_type = "sha256" %}
{% set hash = "68d1a5ed20714e45ee417348ae46de45ab4ed32c6c02ad147cbb9d7ea5293adb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyls = pyls.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - configparser  # [py27]
    - future >=0.14  # [py27]
    - backports.functools_lru_cache  # [py27]
    - jedi >=0.14.1,<0.16
    - python-jsonrpc-server >=0.3.2
    - pycodestyle
    - pydocstyle >=2.0.0
    - pyflakes >=1.6.0
    - pylint
    - python
    - yapf
    - pluggy
    - autopep8
    - mccabe
    - setuptools
    - rope >=0.10.5
    - flake8
    - ujson

test:
  commands:
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol 
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
    - mariusvniekerk
