{% set name = "python-language-server" %}
{% set version = "0.21.4" %}
{% set hash_type = "sha256" %}
{% set hash = "51d238ffefda57b23e4a4cf728532ab0a70b778fc7fa765d7a910fd08683d2fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyls = pyls.__main__:main
    # This recipe has pyls entrypoints

requirements:
  host:
    - python
    - pip
  run:
    - configparser  # [py27]
    - futures       # [py27]     
    - future >=0.14
    - jedi >=0.12
    - python-jsonrpc-server
    - pycodestyle
    - pydocstyle >=2.0.0
    - pyflakes >=1.6.0
    - python
    - yapf
    - pluggy
    - autopep8
    - mccabe
    - setuptools
    - rope >=0.10.5

test:
  commands:
    - pyls --help

about:
  home: https://github.com/palantir/python-language-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 2.7 and 3.4+ implementation of the Language Server Protocol 
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/palantir/python-language-server

extra:
  recipe-maintainers:
    - goanpeca
    - ccordoba12
    - rlaverde
    - andfoy
    - mariusvniekerk
